import { describe, expect, it } from "vitest";
import { parseSpec, bodyModeFor, bodyFieldNames } from "../spec";
import { buildPlan, describeBody, extensionFor, toCurl, type BodyInput } from "../request";
import type { OperationSpec } from "../spec";

const SPEC = JSON.stringify({
  openapi: "3.0.0",
  info: { title: "uploads", version: "1.0.0" },
  paths: {
    "/avatars": {
      post: {
        operationId: "uploadAvatar",
        requestBody: {
          required: true,
          content: {
            "multipart/form-data": {
              schema: {
                type: "object",
                properties: { file: { type: "string", format: "binary" }, caption: { type: "string" } },
              },
            },
          },
        },
        responses: { "201": { description: "created" } },
      },
    },
    "/login": {
      post: {
        operationId: "login",
        requestBody: {
          content: {
            "application/x-www-form-urlencoded": {
              schema: { type: "object", properties: { username: { type: "string" } } },
            },
          },
        },
        responses: { "200": { description: "ok" } },
      },
    },
  },
});

const spec = parseSpec(SPEC, "uploads.json");
const upload = spec.operations.find((op) => op.id.includes("/avatars"))!;
const login = spec.operations.find((op) => op.id.includes("/login"))!;

describe("bodyModeFor", () => {
  it("follows the declared content type rather than asking the user", () => {
    expect(bodyModeFor("multipart/form-data")).toBe("multipart");
    expect(bodyModeFor("application/x-www-form-urlencoded; charset=utf-8")).toBe("form");
    expect(bodyModeFor("application/json")).toBe("text");
    expect(bodyModeFor(undefined)).toBe("text");
  });

  it("reports multipart for an endpoint that only accepts it", () => {
    // The JSON-first preference in pickContent must not hide a file upload.
    expect(bodyModeFor(upload.requestBody?.contentType)).toBe("multipart");
    expect(bodyModeFor(login.requestBody?.contentType)).toBe("form");
  });
});

describe("bodyFieldNames", () => {
  it("lists the parts the schema declares, so the editor opens seeded", () => {
    expect(bodyFieldNames(spec.doc, upload.requestBody?.schema)).toEqual(["file", "caption"]);
  });

  it("is empty rather than throwing when there's no schema", () => {
    expect(bodyFieldNames(spec.doc, undefined)).toEqual([]);
  });
});

describe("buildPlan with structured bodies", () => {
  const plan = (op: OperationSpec, body: BodyInput, vars: Record<string, string> = {}) =>
    buildPlan(op, "https://api.example.com", {}, {}, {}, null, body, vars);

  it("builds a multipart body and does not set Content-Type itself", () => {
    const built = plan(upload, {
      kind: "multipart",
      parts: [
        { name: "file", path: "/tmp/a.png", fileName: "a.png" },
        { name: "caption", value: "hello {{who}}" },
      ],
    }, { who: "world" });

    expect(built.body).toEqual({
      kind: "multipart",
      parts: [
        { name: "file", path: "/tmp/a.png", fileName: "a.png", value: undefined },
        { name: "caption", value: "hello world" },
      ],
    });
    // The boundary is generated by the HTTP client; a value set here would be wrong.
    expect(built.headers["Content-Type"]).toBeUndefined();
  });

  it("builds a form body, keeping repeated keys", () => {
    const built = plan(login, {
      kind: "form",
      fields: [
        { key: "tag", value: "a" },
        { key: "tag", value: "b" },
        { key: "", value: "dropped" },
      ],
    });
    expect(built.body).toEqual({
      kind: "form",
      fields: [
        ["tag", "a"],
        ["tag", "b"],
      ],
    });
    expect(built.headers["Content-Type"]).toBeUndefined();
  });

  it("still sets Content-Type for a text body", () => {
    const built = plan(login, '{"a":1}');
    expect(built.body).toEqual({ kind: "text", text: '{"a":1}' });
    expect(built.headers["Content-Type"]).toBe(login.requestBody?.contentType);
  });

  it("drops a body entirely on GET, whatever the editor holds", () => {
    const get = { ...upload, method: "GET" };
    expect(plan(get, { kind: "multipart", parts: [{ name: "f", path: "/tmp/a" }] }).body).toBeUndefined();
  });

  it("omits parts with no name, rather than sending an unnamed one", () => {
    const built = plan(upload, { kind: "multipart", parts: [{ name: "  ", value: "x" }] });
    expect(built.body).toBeUndefined();
  });
});

describe("toCurl", () => {
  it("exports multipart as -F, with @ for a file", () => {
    const curl = toCurl({
      method: "POST",
      url: "https://api.example.com/avatars",
      headers: {},
      body: {
        kind: "multipart",
        parts: [
          { name: "file", path: "/tmp/a.png", fileName: "a.png" },
          { name: "caption", value: "hi" },
        ],
      },
    });
    expect(curl).toContain("-F 'file=@/tmp/a.png'");
    expect(curl).toContain("-F 'caption=hi'");
  });

  it("exports form fields with --data-urlencode, so curl does the escaping", () => {
    const curl = toCurl({
      method: "POST",
      url: "https://api.example.com/login",
      headers: {},
      body: { kind: "form", fields: [["q", "a b&c"]] },
    });
    expect(curl).toContain("--data-urlencode 'q=a b&c'");
  });
});

describe("describeBody", () => {
  it("records what a multipart request sent without recording the file", () => {
    // History must not accumulate upload payloads; the name is what's useful later.
    expect(
      describeBody({
        kind: "multipart",
        parts: [{ name: "file", path: "/tmp/secret.bin", fileName: "secret.bin" }],
      }),
    ).toBe("file=@secret.bin");
  });

  it("renders form fields readably", () => {
    expect(describeBody({ kind: "form", fields: [["a", "1"], ["b", "2"]] })).toBe("a=1&b=2");
  });
});

describe("extensionFor", () => {
  it("suggests a plausible extension, and nothing when it doesn't know", () => {
    expect(extensionFor("application/pdf")).toBe(".pdf");
    expect(extensionFor("image/png; charset=binary")).toBe(".png");
    // Better no extension than a misleading one.
    expect(extensionFor("application/vnd.acme.thing")).toBe("");
  });
});
